banido = 'https://tenor.com/view/ednaldo-pereira-banido-desbanido-meme-meme-banido-gif-19429642'
desbanido = 'https://tenor.com/view/desbanido-ednaldo-pereira-ednaldo-pereira-banido-gif-19443137'
repositorio = 'https://github.com/Eduardo-Barreto/Marselo-Bot'
readme = 'https://github.com/Eduardo-Barreto/Marselo-Bot/blob/master/README.md'
rickrolling = 'https://youtu.be/dQw4w9WgXcQ'
playlist = 'https://open.spotify.com/playlist/0TWxX4f5AiAfE4FVFj8Vcq?si=d79e763e368743f2'
